name: linting

on: push

defaults:
  run:
    shell: bash

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade black isort

    - name: Version
      run: |
        python3 --version
        black --version
        isort --version

    - name: Run black
      run: |
        pwd
        ls
        black zoidberg
        isort zoidberg

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Apply black/isort changes"
